<script setup lang="ts">
import { defineComponent, h } from 'vue'
import { ThemeProvider, createStyles } from 'antdv-style'

const useStyles = createStyles(({ css, token }) => ({
  panel: css({
    display: 'grid',
    gap: 12,
    padding: 20,
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
    color: token.colorText,
  }),
  title: css({ margin: 0, color: token.colorPrimary, fontSize: 18, fontWeight: 650 }),
  copy: css({ margin: 0, color: token.colorTextSecondary }),
}))

const StyledPanel = defineComponent({
  setup() {
    const s = useStyles()
    return () => h('div', { class: s.styles.panel }, [
      h('h3', { class: s.styles.title }, 'Token-aware styles'),
      h('p', { class: s.styles.copy }, 'This panel is generated by the Vue createStyles composable.'),
    ])
  },
})
</script>

<template>
  <div class="docs-demo">
    <div class="docs-demo__stage">
      <ThemeProvider>
        <StyledPanel />
      </ThemeProvider>
    </div>
    <div class="docs-demo__caption">createStyles reads the nearest ThemeProvider automatically.</div>
  </div>
</template>
